### ISSUE TITLE
How about the results when the camera is higher +1 m

### ISSUE THREAD

**Issue by SophieZhou** [esdolo/FreeVS#2]
In your paper, there are only expriments with lateral view on novel view. What about the results when the camera is higher with 1 m than the origin height. Have you observe any exps on these situation.

**Comment by esdolo** [comment]
We provide an example in which the viewpoint is lifted by 1m in Fig. 1 of the paper.  Our existing observations are consistent with what is shown in Fig. 1, that FreeVS outperforms previous methods on lifted viewpoints. 

However, due to the complete lack of respective training data, FreeVS does indeed produce artifacts in the images when faced with viewpoint elevations greater than 1 m.  We are still exploring solutions to address this issue.

**Comment by SophieZhou** [comment]
> We provide an example in which the viewpoint is lifted by 1m in Fig. 1 of the paper. Our existing observations are consistent with what is shown in Fig. 1, that FreeVS outperforms previous methods on lifted viewpoints.
> 
> However, due to the complete lack of respective training data, FreeVS does indeed produce artifacts in the images when faced with viewpoint elevations greater than 1 m. We are still exploring solutions to address this issue.

Thanks very much.
